# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Dictionary' do
   pod 'AFNetworking', '~> 2.0'
   pod 'MBProgressHUD', '~> 1.0.0'
    
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Dictionary

  target 'DictionaryTests' do
    inherit! :search_paths
    pod 'AFNetworking', '~> 2.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    # Pods for testing
  end

  target 'DictionaryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
